{
 "title": "The Dash Copy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "UPS - Eaton Ellisse ECO 800 USB IEC (800 VA, 500 W)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "UPS Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ups_power_status{instance=\"localhost:8111\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPS Delay Start",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ups_delay_start{instance=\"localhost:8111\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPS Delay Shutdown",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ups_delay_shutdown{instance=\"localhost:8111\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPS Load",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ups_load_percent{instance=\"localhost:8111\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPS Battery Charge",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ups_battery_charge_percent{instance=\"localhost:8111\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPS Battery Duration History",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ups_battery_duration{instance=\"localhost:8111\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPS Status History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "ups_power_status{instance=\"localhost:8111\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPS Load History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ups_load_percent{instance=\"localhost:8111\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPS Battery Charge History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ups_battery_charge_percent{instance=\"localhost:8111\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPS Battery Duration History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ups_battery_duration{instance=\"localhost:8111\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}